server.port=${PORT:8082}

spring.datasource.url=jdbc:mysql://root:LyWboFywMfCXsHnauGMYqUdShOTWzuuo@gondola.proxy.rlwy.net:37020/railway
spring.datasource.username=root
spring.datasource.password=LyWboFywMfCXsHnauGMYqUdShOTWzuuo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

file.upload-dir=uploads/profile