server.port=${PORT:8082}
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://root:keEQgweKnLfbnzlliHQYHUCPEcfzZXcf@sakura.proxy.rlwy.net:22165/railway

spring.datasource.password=keEQgweKnLfbnzlliHQYHUCPEcfzZXcf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

file.upload-dir=uploads/profile